language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-markup' ]; then cd .. && eval "mv $currentfolder generator-markup" && cd generator-markup; fi

